# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param synth.incrementalSynthesisCache C:/Users/yujiarui/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-24512-DESKTOP-MBF5BR3/incrSyn
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7k70tfbv676-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/GithubLocalRepo/CODLAB/Lab8/Lab8.cache/wt [current_project]
set_property parent.project_path D:/GithubLocalRepo/CODLAB/Lab8/Lab8.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/GithubLocalRepo/CODLAB/Lab8/Lab8.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  D:/GithubLocalRepo/CODLAB/Lab8/Lab8.srcs/sources_1/imports/SourceCode/Parameters.v
  D:/GithubLocalRepo/CODLAB/Lab8/Lab8.srcs/sources_1/imports/SourceCode/ALU.v
  D:/GithubLocalRepo/CODLAB/Lab8/Lab8.srcs/sources_1/imports/SourceCode/IdExSegReg/AddrEx.v
  D:/GithubLocalRepo/CODLAB/Lab8/Lab8.srcs/sources_1/imports/SourceCode/ExMemSegReg/AddrMem.v
  D:/GithubLocalRepo/CODLAB/Lab8/Lab8.srcs/sources_1/imports/SourceCode/MemWbSegReg/AddrWb.v
  D:/GithubLocalRepo/CODLAB/Lab8/Lab8.srcs/sources_1/imports/SourceCode/IdExSegReg/BrTarget.v
  D:/GithubLocalRepo/CODLAB/Lab8/Lab8.srcs/sources_1/imports/SourceCode/BranchDecision.v
  D:/GithubLocalRepo/CODLAB/Lab8/Lab8.srcs/sources_1/new/CSR_ALU.v
  D:/GithubLocalRepo/CODLAB/Lab8/Lab8.srcs/sources_1/new/CSR_EX.v
  D:/GithubLocalRepo/CODLAB/Lab8/Lab8.srcs/sources_1/new/CSR_MEM.v
  D:/GithubLocalRepo/CODLAB/Lab8/Lab8.srcs/sources_1/new/CSR_RegisterFile.v
  D:/GithubLocalRepo/CODLAB/Lab8/Lab8.srcs/sources_1/new/CSR_WB.v
  D:/GithubLocalRepo/CODLAB/Lab8/Lab8.srcs/sources_1/new/CSR_immExtend.v
  D:/GithubLocalRepo/CODLAB/Lab8/Lab8.srcs/sources_1/imports/SourceCode/ControllerDecoder.v
  D:/GithubLocalRepo/CODLAB/Lab8/Lab8.srcs/sources_1/imports/SourceCode/IdExSegReg/CtrlEx.v
  D:/GithubLocalRepo/CODLAB/Lab8/Lab8.srcs/sources_1/imports/SourceCode/ExMemSegReg/CtrlMem.v
  D:/GithubLocalRepo/CODLAB/Lab8/Lab8.srcs/sources_1/imports/SourceCode/MemWbSegReg/CtrlWb.v
  D:/GithubLocalRepo/CODLAB/Lab8/Lab8.srcs/sources_1/imports/SourceCode/Cache/DataCache.v
  D:/GithubLocalRepo/CODLAB/Lab8/Lab8.srcs/sources_1/imports/SourceCode/DataExtend.v
  D:/GithubLocalRepo/CODLAB/Lab8/Lab8.srcs/sources_1/imports/SourceCode/GeneralRegister.v
  D:/GithubLocalRepo/CODLAB/Lab8/Lab8.srcs/sources_1/imports/SourceCode/Hazard.v
  D:/GithubLocalRepo/CODLAB/Lab8/Lab8.srcs/sources_1/imports/SourceCode/IfIdSegReg/IR.v
  D:/GithubLocalRepo/CODLAB/Lab8/Lab8.srcs/sources_1/imports/SourceCode/ImmExtend.v
  D:/GithubLocalRepo/CODLAB/Lab8/Lab8.srcs/sources_1/imports/SourceCode/Cache/InstructionCache.v
  D:/GithubLocalRepo/CODLAB/Lab8/Lab8.srcs/sources_1/imports/SourceCode/NPCGenerator.v
  D:/GithubLocalRepo/CODLAB/Lab8/Lab8.srcs/sources_1/imports/SourceCode/IdExSegReg/Op1.v
  D:/GithubLocalRepo/CODLAB/Lab8/Lab8.srcs/sources_1/imports/SourceCode/IdExSegReg/Op2.v
  D:/GithubLocalRepo/CODLAB/Lab8/Lab8.srcs/sources_1/imports/SourceCode/PC.v
  D:/GithubLocalRepo/CODLAB/Lab8/Lab8.srcs/sources_1/imports/SourceCode/IdExSegReg/PcEx.v
  D:/GithubLocalRepo/CODLAB/Lab8/Lab8.srcs/sources_1/imports/SourceCode/IfIdSegReg/PcId.v
  D:/GithubLocalRepo/CODLAB/Lab8/Lab8.srcs/sources_1/imports/SourceCode/IdExSegReg/Reg2Ex.v
  D:/GithubLocalRepo/CODLAB/Lab8/Lab8.srcs/sources_1/imports/SourceCode/ExMemSegReg/Reg2Mem.v
  D:/GithubLocalRepo/CODLAB/Lab8/Lab8.srcs/sources_1/imports/SourceCode/ExMemSegReg/Result.v
  D:/GithubLocalRepo/CODLAB/Lab8/Lab8.srcs/sources_1/imports/SourceCode/MemWbSegReg/WbData.v
  D:/GithubLocalRepo/CODLAB/Lab8/Lab8.srcs/sources_1/imports/SourceCode/RV32ICore.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top RV32ICore -part xc7k70tfbv676-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef RV32ICore.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file RV32ICore_utilization_synth.rpt -pb RV32ICore_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
